const express = require('express');
const router = express.Router();
const mysql = require("../mysql").pool;
const multer   = require("multer");
const path     = require("path");
const fs = require('fs');
const mime = require('mime');


//const multerConfig = multer("../Config/multer");
const storage = multer.diskStorage({
    destination: function (req, file, cb) {
        cb(null, './assets/nascentes/')
    },
    filename: function (req, file, cb) {
        // Extração da extensão do arquivo original:
        const extensaoArquivo = file.originalname.split('.')[1];

        // Cria um código randômico que será o nome do arquivo
        const novoNomeArquivo = require('crypto')
            .randomBytes(64)
            .toString('hex');

        // Indica o novo nome do arquivo:
        cb(null, `${novoNomeArquivo}.${extensaoArquivo}`)
    },
    limits: { fileSize: 25 * 1024 * 1024 },
    fileFilter:(req,file,cb) =>{
        if (file.mimetype !== 'video/jpg' &&file.mimetype !== 'image/png' && file.mimetype !== 'image/jpg' && file.mimetype !== 'image/jpeg') {
            req.file_error = "file not allowed";
            return cb(null,false);
        }
        cb(null, true);
    }
});
const upload = multer({ storage});

        router.post('/',upload.array("file",2), (err,req, res,next) => {
            console.log(JSON.stringify(req.file));  
            console.log(req.file);//this will be automatically set by multer
         
            //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
            fs.readFile(req.file.path,(err, contents)=> {
             if (err) {
             console.log('Error: ', err);
             return res.status(400).json({
                            erro:true,
                            mensagem:"Erro Upload não realizado com sucesso!"
                        })
            }else{
             console.log('File contents ',contents);
             return res.status(204).json({
                erro:false,
                mensagem:"upload realizou com sucesso!"
             })
            }
           });
          });
        router.post('/upload', upload.array('file', 2), (req, res) => {
            console.log('file', req.files);
            console.log('path_1', req.files[0].path);
            console.log('path_2', req.files[1].path);
            const foto_2= req.files[0].path;
            const foto_5= req.files[1].path;
            const{
                user,
                username,
                useravatar,
                redesocial,
                status,
                percentual,
                categoria,
                fontename,
                latitude,
                longitude,
                token
            }= req.body;
            console.log('body', latitude);
            mysql.getConnection((error, conn)=>{
       
                conn.query(
                    `INSERT INTO 
                    fontes(
                        user,
                        username,
                        useravatar,
                        redesocial,
                        status,
                        percentual,
                        categoria,
                        fontename,
                        latitude,
                        longitude,
                        foto_2,
                        foto_5,
                        token
                    )
                    values (?,?,?,?,?,?,?,?,?,?,?,?,?)  
                    `,[
                        user,
                        username,
                        useravatar,
                        redesocial,
                        status,
                        percentual,
                        categoria,
                        fontename,
                        latitude,
                        longitude,
                        foto_2,
                        foto_5,
                        token  
                    ],
                       (error, result, fields)=>{
                      
                           conn.release();
                           if(error){
                              
                            return   res.status(500).send({
                                   error:error,
                                   response: null
                               });
                           }
                           if(result.length==0){
                              
                               return res.status(404).send({
                                  
                                mensagem:"Não foi possivel salvar os dados"
                                   })
                           }
                           res.status(201).send({
                            mensagem:"Fonte Salva com Sucesso!",
                            id:result.insertId
                        })
                       }
                )
        })
          });


module.exports = router;